
# Default Linux Kernel directory
ifeq (,$(KERNDIR))

endif

# Default Linux include directory
ifeq (,$(LINUX_INCLUDE))
LINUX_INCLUDE := $(KERNDIR)/include
endif

PREFIX_CROSS_COMPILE := $(KERNEL_ROOT_DIR)/toolchain/gcc/linux-x86/arm/gcc-linaro-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
ARCH := arm
KBUILD_VERBOSE = 1

export ARCH KBUILD_VERBOSE

ifneq ($(targetplat),user)
include ${KERNEL_ROOT_DIR}/buildroot/make/Makefile.linux-qemu-4_19
endif